language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=$HOME/devkitPro

cache:
  directories:
    - "$HOME/.local"

addons:
  apt:
    packages:
    - p7zip-full

before_install:
  - mkdir -p "${DEVKITPRO}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i /tmp/devkitpro-pacman.deb; fi
  - yes | sudo dkp-pacman -Syu devkitPPC
  - export DEVKITPPC=/opt/devkitpro/devkitPPC

install:
  - 7z x -y ./libs/portlibs.zip -o${DEVKITPRO}

script:
  - make